# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20160601_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nazwa Klienta')),
                ('address', models.CharField(max_length=1023, verbose_name='Adres')),
                ('status', models.IntegerField(choices=[(0, 'Nowe'), (1, 'Anulowane'), (2, 'Zrealizowane')], default=0)),
            ],
            options={
                'verbose_name': 'Zamowienie',
                'verbose_name_plural': 'Zamowienia',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Zamowiony produkt',
                'verbose_name_plural': 'Zamowione produkty',
            },
        ),
    ]
